### ISSUE TITLE
PIN only

### ISSUE THREAD

**Issue by jozephbrasil** [archiecobbs/mod-authn-otp#33]
How to exclude an user from OTP authentication and set PIN only? Is it possible?
For example, instead of HOTP/T30, set it as PINONLY or something like that for a specific user.

**Comment by archiecobbs** [comment]
That's not currently possible to do directly.

However, PIN-only authentication is equivalent to plain username+password authentication, so you can get the same effect by setting up an alternate authentication provider using a normal `htpasswd` file, etc., and then using the `OTPAuthFallThrough` configuration option to allow authentication requests to fall through to it.
