### ISSUE TITLE
[Clarification request]

### ISSUE THREAD

**Issue by Wikinaut** [archiecobbs/mod-authn-otp#34]
I successfully installed the module, but I don't know how to get it working with the

* https://github.com/0xbb/otp-authenticator

Please can you explain (in detail) in the readme or wiki, how the "account" is to be created on the software i.e. mobile token authenticator ?

**Comment by archiecobbs** [comment]
Users are created by editing the [UsersFile](https://github.com/archiecobbs/mod-authn-otp/wiki/UsersFile). 

You will need to extract from the app the following:

- The hexadecimal secret 
- Looks like it uses time based, 30 second tokens
- Looks like it produces 6 digit decimal values

So your users would be configured as `HOTP/T30`.

I'm not familiar with the app or how to extract the hex secret.

**Comment by Wikinaut** [comment]
I tought that MOTP had to be used. Am I wrong?

**Comment by Wikinaut** [comment]
Sorry, your answer was not yet helpful. The https://github.com/0xbb/otp-authenticator app read via the camera an QR code with the "secret" and then adds an account. 

My question is simply, how _your_ module  can supply the needed data, i.e. account name and secret, to the authenticator app.

**Comment by archiecobbs** [comment]
It doesn't do that. This software is only for verifying token values, not installing or deploying them.

**Comment by Wikinaut** [comment]
Can you explain how seed (in your UserFile) is calculated, it appears to be SHA-1( strtoupper( shared secret ) ) but this does not work for me when using the https://github.com/kckrinke/onetimepad app .

**Comment by Wikinaut** [comment]
I found deep in your documentation a link to 
https://www.cnysupport.com/index.php/free-stuff/using-google-authenticator-with-apache-mod_authn_otp which allows to create seeds for the UserFile.
