### ISSUE TITLE
INSTALL doc is incomplete

### ISSUE THREAD

**Issue by ghoffart** [archiecobbs/mod-authn-otp#35]
The file INSTALL lists detailed each step required to get the software installed. But the step "./autogen.sh" is missing.

**Comment by archiecobbs** [comment]
The `INSTALL` file instructions are for people who have downloaded the distribution tar file.

On the other hand, the `autogen.sh` script is for developers working with the source code; they supposedly already know what they're doing.

Let me know if this doens't clear up the question/issue.

**Comment by ghoffart** [comment]
I downloaded the newest tar.gz file in the "Release" section. There, the "configure" is missing. Isn’t this the distribution tar file?

**Comment by archiecobbs** [comment]
Oh, I guess that's confusing. GitHub puts those links up there automatically for each created tag. I don' t know how to that page that off.

The "real" releases are on the [Downloads](https://github.com/archiecobbs/mod-authn-otp/wiki/Downloads) wiki page.

**Comment by ghoffart** [comment]
Aaaah! That’s also _way_ newer than in "Releases". Thanks. I wouldn’t have assumed that the Releases are not actually in 'Releases' ;-)
