### ISSUE TITLE
Defunct #define / URL in config.log

### ISSUE THREAD

**Issue by ghoffart** [archiecobbs/mod-authn-otp#36]
#define PACKAGE_BUGREPORT "http://mod-auth-otp.googlecode.com/"

won’t work any longer.

**Comment by archiecobbs** [comment]
Already fixed in ba79ddfb.

**Comment by archiecobbs** [comment]
We do need to put out a new release however, to make this change public.

**Comment by archiecobbs** [comment]
1.1.8 has been released.
