### ISSUE TITLE
use mod-authn-otp with aws ALB

### ISSUE THREAD

**Issue by cleonte** [archiecobbs/mod-authn-otp#41]
Hi,

i would like to use mod otp with AWS ALB (aplication load balancer), but i can't since i see in the logs the ip of the load balacner instead of the ip of the client, any workaround for this?

Cheers

**Comment by tessus** [comment]
This is a very good question, since it also applies to reverse proxy setups.
I am also interested in the answer. ;-)

**Comment by tessus** [comment]
@cleonte in this case you have to add X-Forward* headers on the load balancer...

**Comment by cleonte** [comment]
and i ca use it on the otp module?

**Comment by archiecobbs** [comment]
The `X-Forwarded-For` header is likely already being added by the load balancer. Check your AWS docs.

@cleonte I'm pretty sure you can configure Apache to only apply OTP authentication if the `X-Forwarded-For` header doesn't match some regular expression.

**Comment by cleonte** [comment]
thank you for your help, will try to see if i can use that

**Comment by tessus** [comment]
@cleonte also have a look at https://blog.trikoder.net/auth-behind-reverse-proxy-3b3f81897cb7
