### ISSUE TITLE
build on debian

### ISSUE THREAD

**Issue by alexbodn** [archiecobbs/mod-authn-otp#47]
hello archie and thank you for maintaining this module i'm considering to use.
i've just built it on a debian machine and had to make 
the following small changes.
first, i had to install libssl-dev.
then, the included patch fixed include files location in otplock.c.
also, i made a .gitignore file for managing source only.
my patch is attached.
[patches.diff.gz](https://github.com/archiecobbs/mod-authn-otp/files/10583281/patches.diff.gz)

hope this helps,
alex

**Comment by archiecobbs** [comment]
Thanks for the info.

I don't keep track of build instructions for specific distributions in this project; that's the job of the distributions themselves.

Maybe you could ask the Debian folks to add mod_authn_otp to their list of supported packages.

See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735059

Cheers.

**Comment by alexbodn** [comment]
hello archie,

as far as i remember, the building instructions you gave were for a debian
based distro.
and otplock.c is a new file.
i have just built the module there and had to do the mentioned amendments.
I'll see what i can do about distribution with debian.

enjoy,
alex

**Comment by archiecobbs** [comment]
> as far as i remember, the building instructions you gave were for a debian based distro.

Hmm, maybe I did but forgot. If so, sorry about that (I don't work with Debian anymore).
